baseURL = "https://markadell.me/"
title = "Mark Adel"
languageCode = "en-us"
paginate = 20
Copyright = "Copyright © 2024 Mark Adel. All rights reserved."

[services]
  [services.googleAnalytics]
    ID = 'G-KV30R9H9HV'
  [services.disqus]
    shortname = 'markadel'

[menu]

  [[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 1

  [[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 3

  [[menu.main]]
  name = "Jottings"
  url = "/jottings/"
  weight = 2

  # [[menu.main]]
  # name = "Projects"
  # url = "/projects/"
  # weight = 3

[params]
  author = "Mark Adel"
  defaultTheme = "dark"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  HideFooter = false
  ShowToc = false
  ShowWordCount = false
  hideAuthor = true
  disableScrollToTop = false
  hideSummary = true
  disableFingerprinting = false
  enableComments = true

  [params.homePage]
  title = "Mark Adel"
  description = "Hello there! I'm Mark, a software engineer based in Egypt. This is my little corner of the internet where I will be sharing my thoughts and experiences."
  imageUrl = ""
  imageTitle = ""

  [params.assets]
  favicon = "https://markadel.me/images/favicon.ico"
  favicon16x16 = "https://markadel.me/images/favicon-16x16.png"
  favicon32x32 = "https://markadel.me/images/favicon-32x32.png"
  apple_touch_icon = "https://markadel.me/images/apple-touch-icon.png"
  safari_pinned_tab = "https://markadel.me/images/apple-touch-icon.png"
  disableHLJS = true


  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/MarkAdell"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/mark-adel-8116a8ab/"

  [[params.socialIcons]]
  name = "dev"
  url = "https://dev.to/markadel"

enableInlineShortcodes = true
enableRobotsTXT = true
enableEmoji = true
pygmentsUseClasses = true

[minify]
disableXML = true
